
import { ParsedListingData, AuditReport } from '../types';

/**
 * Escapes a string value for CSV format.
 * Handles commas, double quotes, and newlines by enclosing the value in double quotes
 * and doubling any internal double quotes.
 */
function escapeCsv(value: string | number | undefined | null): string {
  if (value === undefined || value === null) {
    return '';
  }
  let strValue = String(value);
  if (strValue.includes(',') || strValue.includes('"') || strValue.includes('\n') || strValue.includes('\r')) {
    return `"${strValue.replace(/"/g, '""')}"`;
  }
  return strValue;
}

/**
 * Generates CSV content from parsed listing data and audit report.
 * Organizes the data into logical sections with clear headers for readability.
 */
export function generateCsvContent(parsedData: ParsedListingData, auditReport: AuditReport): string {
  const rows: string[][] = [];

  // Add application metadata
  rows.push(['Report Generated By', 'CVC Listing Optimisation Tool']);
  rows.push(['Report Date', new Date().toLocaleDateString('en-GB')]); // UK date format
  rows.push([]); // Empty row for separation

  // Section: General Listing Information
  rows.push(['SECTION: General Listing Information']);
  rows.push(['Field', 'Value']);
  rows.push(['Original Title', parsedData.title]);
  rows.push(['Price', parsedData.price]);
  // Truncate description HTML and strip tags for CSV to avoid excessively long cells and HTML interference
  const descriptionSnippet = parsedData.descriptionHtml.replace(/<[^>]*>?/gm, '').replace(/(\r\n|\n|\r)/gm, ' ').substring(0, 500);
  rows.push(['Original Description (Snippet)', escapeCsv(descriptionSnippet + (parsedData.descriptionHtml.length > 500 ? '... (truncated)' : ''))]);
  rows.push(['Overall Audit Score', auditReport.overallScore.toFixed(2)]); // Format score to 2 decimal places
  rows.push([]);

  // Section: Title Strategy
  rows.push(['SECTION: Title Strategy']);
  rows.push(['Field', 'Value']);
  rows.push(['Current Title', auditReport.titleStrategy.currentTitle]);
  rows.push(['Recommended Title', auditReport.titleStrategy.recommendedTitle]);
  rows.push(['Title Score', auditReport.titleStrategy.score.toFixed(2)]);
  rows.push([]);

  // Section: Item Specifics Recommendations
  rows.push(['SECTION: Item Specifics Recommendations']);
  rows.push(['Type', 'Details']);
  if (auditReport.itemSpecificsRecommendations.additions.length > 0) {
    rows.push(['Additions', auditReport.itemSpecificsRecommendations.additions.join('; ')]);
  } else {
    rows.push(['Additions', 'No additions recommended.']);
  }

  if (auditReport.itemSpecificsRecommendations.corrections.length > 0) {
    auditReport.itemSpecificsRecommendations.corrections.forEach((correction, index) => {
      rows.push(
        [
          index === 0 ? 'Corrections' : '',
          `${correction.label}: Current "${correction.current_value}" -> Recommended "${correction.recommended_value}"`
        ]
      );
    });
  } else {
    rows.push(['Corrections', 'No corrections recommended.']);
  }
  rows.push([]);

  // Section: Photo Recommendations
  rows.push(['SECTION: Photo Recommendations']);
  // Strip HTML tags and normalize newlines for photo advice
  const photoAdviceClean = auditReport.photoAdvice.replace(/<[^>]*>?/gm, '').replace(/(\r\n|\n|\r)/gm, ' ').substring(0, 1000);
  rows.push(['Advice', escapeCsv(photoAdviceClean + (auditReport.photoAdvice.length > 1000 ? '... (truncated)' : ''))]);
  rows.push([]);

  // Section: Description Rewrite
  rows.push(['SECTION: Description Rewrite']);
  // Strip HTML tags and normalize newlines for description rewrite
  const descriptionRewriteClean = auditReport.descriptionRewrite.replace(/<[^>]*>?/gm, '').replace(/(\r\n|\n|\r)/gm, ' ').substring(0, 2000);
  rows.push(['Rewritten Content', escapeCsv(descriptionRewriteClean + (auditReport.descriptionRewrite.length > 2000 ? '... (truncated)' : ''))]);
  rows.push([]);

  // Section: Logistics
  rows.push(['SECTION: Logistics']);
  rows.push(['Field', 'Value']);
  rows.push(['Postage Policy', auditReport.logistics.postagePolicy]);
  rows.push(['Return Policy', auditReport.logistics.returnPolicy]);
  rows.push(['Logistics Score', auditReport.logistics.score.toFixed(2)]);
  rows.push([]);

  // Section: eBay Advertising
  rows.push(['SECTION: eBay Advertising']);
  rows.push(['Field', 'Value']);
  rows.push(['Recommended Campaign Type', auditReport.ebayAdvertising.recommendedCampaignType]);
  rows.push(['Campaign Info', auditReport.ebayAdvertising.campaignInfo]);
  rows.push(['Exact Match Keywords', auditReport.ebayAdvertising.exactMatchKeywords.join('; ')]);
  rows.push(['Phrase Match Keywords', auditReport.ebayAdvertising.phraseMatchKeywords.join('; ')]);
  rows.push(['Broad Match Keywords', auditReport.ebayAdvertising.broadMatchKeywords.join('; ')]);
  
  rows.push(['Setup Instructions']);
  auditReport.ebayAdvertising.setupInstructions.forEach((instruction, index) => {
    rows.push([`Step ${index + 1}`, instruction]);
  });
  rows.push([]);

  // Join all rows and cells to form the final CSV string
  return rows.map(row => row.map(cell => escapeCsv(cell)).join(',')).join('\n');
}
